version: "3.9"

services:
  
  
  pihole:
  # More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
    container_name: pihole
    image: pihole/pihole:2022.05
    # For DHCP it is recommended to remove these ports and instead add: network_mode: "host"
    ports:
      - ${PORT_PIHOLE_WEB}:80
      - ${PORT_PIHOLE_TCP}:53/tcp
      - ${PORT_PIHOLE_UDP}:53/udp
    #  - ${PORT_PIHOLE_DHCP}:67/udp # Only required if you are using Pi-hole as your DHCP server

    environment:
      TZ: ${TZ}
      WEBPASSWORD: ${PIHOLE_PASSWORD}
      FTLCONF_REPLY_ADDR4: ${PIHOLE_FTLCONF_REPLY_ADDR4}
      PIHOLE_DNS_: ${PIHOLE_DNS}
      DHCP_ACTIVE: ${PIHOLE_DHCP_ACTIVE}

      TEMPERATUREUNIT: ${PIHOLE_TEMPUNIT}
      WEBTHEME: ${PIHOLE_WEBTHEME}

    volumes:
      - ${CONFIGDIR}/pihole/pihole:/etc/pihole
      - ${CONFIGDIR}/pihole/dnsmasq.d:/etc/dnsmasq.d  
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities

    cap_add:
      - NET_ADMIN # Recommended but not required (DHCP needs NET_ADMIN)      
    restart: unless-stopped


####################
# Back End Services
####################

  duckdns:
    container_name: duckdns
    image: ghcr.io/linuxserver/duckdns

    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
      SUBDOMAINS: ${DUCKDNS_SUBDOMAINLIST}
      TOKEN: ${DUCKDNS_TOKEN}
      LOG_FILE: ${LOGDIR}/duckdns.log #optional

    volumes:
      - ${CONFIGDIR}/duckdns:/config #optional

    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 32M  
    restart: unless-stopped

  socky_proxy:
    container_name: socky_proxy
    image: ghcr.io/tecnativa/docker-socket-proxy:0.1 # A security-enhanced proxy for the Docker Socket.

    privileged: true
  
    networks:
      - socky_proxy-net

    ports:
      - ${PORT_SOCKY_PROXY}:2375

    environment:
      # Variables match the URL prefix (i.e. AUTH blocks access to /auth/* parts of the API, etc).
      #   0 - revoke access
      #   1 - grant access
      CONTAINERS: 1
      INFO: 1

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 32M

    restart: always

####################
# Docker Environment
####################

networks:

  socky_proxy-net:
    name: socky_proxy-net
