version: "3.9"

services:
  ####################
  # Network Services
  ####################

  pihole:
  # More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
    container_name: pihole
    hostname: pihole
    image: pihole/pihole:latest
    
    depends_on:
      - unbound

    networks:
      dns-net:
        ipv4_address: 172.20.0.2

    # For DHCP it is recommended to remove these ports and instead add: network_mode: "host"
    ports:
      - ${PORT_PIHOLE_WEB:-80}:80
      - ${PORT_PIHOLE_WEBSSL:-443}:443
      - ${PORT_PIHOLE_TCP:-53}:53/tcp
      - ${PORT_PIHOLE_UDP:-53}:53/udp
    #  - ${PORT_PIHOLE_DHCP:-67}:67/udp # Only required if you are using Pi-hole as your DHCP server

    environment:
      TZ: ${TZ}
      WEBPASSWORD: ${PIHOLE_PASSWORD}
      FTLCONF_REPLY_ADDR4: ${PIHOLE_FTLCONF_REPLY_ADDR4}
      PIHOLE_DNS_: unbound#5053
      DHCP_ACTIVE: ${PIHOLE_DHCP_ACTIVE:-false}
      PIHOLE_DOMAIN: ${PIHOLE_DOMAIN:-lan}

      TEMPERATUREUNIT: ${PIHOLE_TEMPUNIT:-c}
      WEBTHEME: ${PIHOLE_WEBTHEME:-default-dark}

    volumes:
      - ${CONFIGDIR}/pihole/pihole:/etc/pihole
      - ${CONFIGDIR}/pihole/dnsmasq.d:/etc/dnsmasq.d  
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities

    cap_add:
      - NET_ADMIN # Recommended but not required (DHCP needs NET_ADMIN)
    restart: unless-stopped

  wireguard:
    container_name: wireguard
    image: lscr.io/linuxserver/wireguard:latest

    ports:
      - ${PORT_VPN:-51820}:51820/udp

    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}

      PEERS: 1 #optional

      SERVERURL: ${WG_SERVERURL:-auto} #optional
      SERVERPORT: ${WG_SERVERPORT:-51820} #optional
      PEERDNS: pihole#53
      ALLOWEDIPS: ${WG_ALLOWED_IPS:0.0.0.0/0} #optional
      LOG_CONFS: true #optional

    volumes:
      - ${CONFIGDIR}/wireguard:/config
      - /lib/modules:/lib/modules

    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    restart: unless-stopped
  
  
  unbound:
    container_name: unbound
    image: mvance/unbound-rpi:latest
    networks:
      dns-net:
        ipv4_address: 172.20.0.3

    volumes:
      - ${CONFIGDIR}/unbound:/opt/unbound/etc/unbound

    healthcheck:
      disable: true
    restart: unless-stopped


####################
# Back End Services
####################

  duckdns:
    container_name: duckdns
    image: ghcr.io/linuxserver/duckdns

    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
      SUBDOMAINS: ${DUCKDNS_SUBDOMAINLIST}
      TOKEN: ${DUCKDNS_TOKEN}

    volumes:
      - ${CONFIGDIR}/duckdns:/config #optional

    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 32M  
    restart: unless-stopped

####################
# Docker Environment
####################

networks:
  dns-net:
    name: dns-net
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
